### ISSUE TITLE
A minimal metashell branch?

### ISSUE THREAD

**Issue by mikael-s-persson** [sabel83/metashell#9]
Hi guys,

I understand the whole idea that metashell wants to tailor to the widest audience (i.e., novice programmers), and that's the reason (AFAIK) for metashell's code-base to include lots and lots of third-party sources (all of boost, libstdc++ (mingw), protobuf and others), in addition to llvm/clang/templight. I get that the idea is to provide a kind of all-in-one "painless" installation/build process (in terms of configurations needed, not in terms of time needed). That's all fine.

However, I'm not a novice and I'm used to dealing with external dependencies and related configurations, like most experienced programmers. Therefore, I don't really benefit from this, and I only get the downsides. Mainly, I don't like the idea that metashell pulls in megabytes of code (with only a ridiculously small fraction being metashell's code itself), and builds gigabytes of code that I already have installed or built on my system. I'm also hesitant to use the kinds of build scripts (like your build.sh) that tinker with my systems and make decisions that annoy me. And in the prospect of contributing to metashell, or just playing around with its code, or just keeping up-to-date with the revision history, I can't imagine having to contend with the massive (semi-regular) updates to the third-party sources mixed in with the relevant revisions in metashell's own code.

To solve this, I would propose that there should be two "master" branches. One would be the current "novice-friendly" master branch from which full releases can be generated. Another could be a "master-minimal" branch which contains only metashell's code, and relies on existing installs or builds for boost, libstdc++, protobuf, templight, llvm/clang, etc... that the user is required to get on his own (as usual). That would require a few bits of cmake-magic and configurability (again, as usual). I think that this way, developers of metashell could essentially work off this more reduced and manageable branch, and the changes would be easily mergeable into the full master branch (and the updates of the third party sources can be done there, separately from the master-minimal branch). The master-minimal would also serve as the branch to clone for those who, like me, would prefer a much more minimal set of sources, with more control on the build and the ability to configure it to use the external library installs / builds that they want.

What say you?

**Comment by r0mai** [comment]
Hi Mikael,

I completely understand your concerns, and I agree, that the inclusion of third party libraries makes developing little bit more difficult _sometimes_.

On the other hand, besides the easy build interface (build.sh) for the users, we also have a predictable build environment. And this is very big win because, we don't have to support multiple versions of boost, clang or templight. For example, the last time I checked, metashell code doesn't compile with the latest boost libraries (for some reasons I didn't dig into). Using build.sh (or following the README instructions, these two should be equivalent) you should be able to build and install metashell on every supported OS regardless of what kind of libraries you have on your system (windows is an exception here of course).

These are the third party libraries we have in the repository:
* __boost__: as I noted above, we need a specific version.
* __clang__: having this in repo is a big pain for us as well. A full llvm+clang build cannot be done in travis due to time constraints, so we can't test mdb functionality there. 
  I think that as soon as we have a clang release which can be used with templight without any source code patches, we will remove the clang source from the repository.
* __protobuf__: This is not in the repository and will most likely never be. I'm planing to port your ThinProtobuf library to metashell to eliminate this dependency.
* and there are some other libraries which are required to make things work on particular platforms

As for your proposal:
Having two branches wouldn't solve the problem with the repository size, unless you cook up some clever git command to only clone a single branch, but not too deep (this is possible btw).
Also, I believe this would have the opposite effect and make development more difficult. Most non trivial projects I worked on either had the third parties included in the repository next to the source code, or it had the build system download exact versions of the libraries. Logically both of these boil down to the same thing: predictable and reproducible build environment.

Supporting even more build configuration would make a release cycle _long_. The release of 2.0.0 took Abel about 3-4 weeks to go through all the supported platforms and fix things.

Managing two branches with completely different contents is also a nightmare.

Currently we don't have any documentation on how we handle or do dependency updates while developing (which you're afraid of). But we can help that quite easily :)

There is one more scenario that might interest you: You might want to use mdb to test templight while developing. I think this should be as easy as pointing metashell to your templight binary (with --clang).
I'll have to double check it though if you're interested. (currently, metashell uses libclang, and mdb uses the templight binary itself. This asymmetry is of course just a temporary thing as we're in the middle of major refactorings atm)

Abel can answer the question on how difficult it would be to insert customization points into the cmake files, so you can explicitly specify library locations. He created 99.9% of the cmake files.

Regards,
András

P.S. I'm really tired, I hope I managed to transfer my thoughts successfully ;)

**Comment by sabel83** [comment]
Hi Mikael,

András summarised it nicely why we are handling the dependencies in Metashell they way we do.

There are hooks in the build system of Metashell that allow you to use your own version of Clang. You might take a look at cmake/Modules/FindClang.cmake, which describes the CMake variables to use to tell where to look for Clang in comments. The top level CMakeLists.txt adds the "internal" version of Clang to the end of the search path, so if you specify your own in the CLANG_* variables when you run cmake, that will be chosen.

I agree, that it is not well (if at all :)) documented, how to use a custom Clang/Templight build. I'll change that. I believe that there should be one (master) branch and hooks for the "advanced developers" for experimenting with custom builds of the dependencies. (I think it is more about how much effort you would like to spend on configuring all the dependencies when you are about to change things in Metashell's own code, rather than how "advanced" you are).

Regards,
  Ábel

**Comment by sabel83** [comment]
Hi Mikael,

I've added instructions on how to build Metashell against a custom Clang build. I've tested it against the latest version of Clang + your Templight patch on Ubuntu. Let us know if this help.

You can find the instructions here: http://metashell.readthedocs.org/en/latest/getting_metashell/build/#building-against-custom-clang-build

Regards,
  Ábel

**Comment by robertramey** [comment]
I am very interested in using the program to help debug my TMP based library.  I use OS X Yosemite.  I downloaded the the binary and ran the installer. It brings up  a box with two folders application and usr.  But it's not at clear what do I have to do at this point.  I can open the "Application" folder which is only a short cut to the normal OS X Application folder.  The "usr" folder looks like some code - but it's not clear what I'm supposed to do with this.  How about some more complete instructions?

I am very, very invested in this having attended the related session at C++Now 2014.

Robert Ramey

**Comment by r0mai** [comment]
Hi Robert,

I believe you have to drag usr into Application to install. You're right, the documentation could see some improvement (will do it soon).
Either way, I'd advise you to compile metashell from source. It should be very easy to do, and there have been a bunch of new features and performance improvements since 2.0.0.

For compiling from source please see: http://metashell.readthedocs.org/en/latest/getting_metashell/build/#building-metashell-on-os-x
If you run into any issues with that, please let us know, so we can improve the docs.

For the new features you'll get this way, see:
http://metashell.readthedocs.org/en/latest/about/changelog/

Regards,
Andras
